### PR TITLE
Fix working directory browse button disabled issue

### LINKED ISSUE #639: Working directory file browse button disabled
When trying to select the path for the working directory(in the run/debug configurations) a file chooser window can't be opened because browse button is disabled.

### PR DESCRIPTION
**Pull request by RAVEENSR**
Resolves #639

### CODE REVIEW

File: src/main/java/org/ballerinalang/plugins/idea/runconfig/ui/BallerinaApplicationSettingsEditor.java [hunk 1]
```diff
@@ -54,6 +54,7 @@ public BallerinaApplicationSettingsEditor(Project project) {
         myProject = project;
         installRunKindComboBox();
         BallerinaRunUtil.installBallerinaWithMainFileChooser(project, myFileField.getComponent());
+        BallerinaRunUtil.installBallerinaWithMainFileChooser(project, myWorkingDirectoryField.getComponent());
```
Comment (Shan1024) [inline src/main/java/org/ballerinalang/plugins/idea/runconfig/ui/BallerinaApplicationSettingsEditor.java]: This is incorrect. We need to be able to select a directory as the current working directory. But this will only show the Ballerina files with **main** function in it and we cannot select a directory as well. So you will have to create a new `FileChooserDescriptor` for this.
